### ISSUE TITLE
OpenAI API Key Shown

### ISSUE THREAD

**Issue by LilBroCodes** [catid/textworld_llm_benchmark#1]
Don't know if there is some specific reason for this not being hidden but your OpenAI API Key is Shown in [llm_play_textworld.py](https://github.com/catid/textworld_llm_benchmark/blob/38dd2f29e9c78e4000c49579d29f3fedc91b0e34/llm_play_textworld.py#L277)

**Comment by catid** [comment]
Thanks removed!
